-- MySQL Script generated by MySQL Workbench
-- Tue May 26 10:32:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

create database reproducion;

use reproducion;
-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Animal (
  `cod_animal` INT NOT NULL AUTO_INCREMENT,
  `crotal` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `apelido_1` VARCHAR(50) NOT NULL,
  `apelido_2` VARCHAR(50) NOT NULL,
  `data_nac` DATE NOT NULL,
  `raza` VARCHAR(50) NOT NULL,
  `carta_rexistro` VARCHAR(200) NULL,
  `ficheiro_xenomica` VARCHAR(200) NULL,
  `ficheiro_acoplamento` VARCHAR(200) NULL,
  `vaca` BIT NULL,
  PRIMARY KEY (`cod_animal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Toro (
  `cod_toro` INT NOT NULL AUTO_INCREMENT,
  `crotal` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `apelido_1` VARCHAR(50) NOT NULL,
  `apelido_2` VARCHAR(50) NOT NULL,
  `dosis_stock` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`cod_toro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Inseminacion
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Inseminacion (
  `cod_inseminacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cod_animal` INT NOT NULL,
  `cod_toro` INT NOT NULL,
  PRIMARY KEY (`cod_inseminacion`),
  INDEX `cod_animal_idx` (`cod_animal` ASC) VISIBLE,
  INDEX `cod_toro_idx` (`cod_toro` ASC) VISIBLE,
  CONSTRAINT `cod_animal`
    FOREIGN KEY (`cod_animal`)
    REFERENCES Animal (`cod_animal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_toro`
    FOREIGN KEY (`cod_toro`)
    REFERENCES Toro (`cod_toro`)
    ON DELETE Cascade
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Revision (
  `cod_revision` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `positivo` BIT NOT NULL,
  `segunda` BIT NOT NULL,
  `macho` BIT ,
  `cod_animal` INT NOT NULL,
  PRIMARY KEY (`cod_revision`),
  INDEX `cod_animal_idx` (`cod_animal` ASC) VISIBLE,
    FOREIGN KEY (`cod_animal`)
    REFERENCES Animal (`cod_animal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Secado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Secado (
  `cod_secado` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cod_animal` INT NOT NULL,
  PRIMARY KEY (`cod_secado`),
  INDEX `cod_animal_idx` (`cod_animal` ASC) VISIBLE,
    FOREIGN KEY (`cod_animal`)
    REFERENCES Animal (`cod_animal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Parto (
  `cod_parto` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(45) NULL,
  `sexo` BIT NULL,
  `cod_animal` INT NOT NULL,
  PRIMARY KEY (`cod_parto`),
  INDEX `cod_animal_idx` (`cod_animal` ASC) VISIBLE,
    FOREIGN KEY (`cod_animal`)
    REFERENCES Animal (`cod_animal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
